#!/usr/bin/env ruby
require './sh/support/allocation_benchmarker'
require './sh/support/allocation_summary_table'

results = Dir['apps/*.ru'].map do |file|
  tracker = AllocationsBenchmarker.new(file)
  tracker.human_output
  Object.send(:remove_const, :APP)
  Object.send(:remove_const, :HelloWorld) if Object.constants.include?(:HelloWorld)
  Object.send(:remove_const, :HelloController) if Object.constants.include?(:HelloController)
  tracker.machine_result
end

summary_table = AllocationSummaryTable.new(results)
puts summary_table.render

File.open('results/memory.md', 'w') do |f|
  f.puts summary_table.render_markdown
end
summary_table.replace_readme('mem_table')
